apiVersion: v1
kind: Service
metadata:
  name: ros2-bridge
  labels:
    app: ros2-bridge
spec:
  type: LoadBalancer
  selector:
    app: ros2-bridge
  ports:
    - protocol: TCP
      port: 50002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ros2-bridge
  labels:
    app: ros2-bridge
spec:
  selector:
    matchLabels:
      app: ros2-bridge
  template:
    metadata:
      labels:
        app: ros2-bridge
    spec:
      containers:
      - name: ros2-bridge
        image: rmf-web/ros2-bridge
        imagePullPolicy: Never # remove this in a real deployment
        args:
          - --host=0.0.0.0
          - --port=50002
          - --publicKey=/configmap/jwt-cert.pem
        ports:
          - containerPort: 50002
        volumeMounts:
          - mountPath: /configmap
            name: jwt-cert
      volumes:
        - name: jwt-cert
          configMap:
            name: jwt-cert
      hostNetwork: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ros2-bridge
  labels:
    app: ros2-bridge
spec:
  tls:
    - hosts:
      - example.com
  rules:
    - host: example.com
      http:
        paths:
          - path: /ros2
            pathType: Prefix
            backend:
              service:
                name: ros2-bridge
                port:
                  number: 50002
