apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  project: rmf-web-example-full

bases:
  - ../example-lite
  - ../base/reporting-server
  - ../base/reporting

resources:
  - cronjobs.yaml
  - fluentd-configmap.yaml

images:
  - name: rmf-web/rmf-server
    newTag: ${RMF_SERVER_TAG}
  - name: rmf-web/dashboard
    newTag: ${DASHBOARD_TAG}
  - name: rmf-web/reporting-server
    newTag: ${REPORTING_SERVER_TAG}
  - name: rmf-web/reporting
    newTag: ${REPORTING_TAG}

configMapGenerator:
  - name: jwt-pub-key
    files:
      - keycloak/jwt-pub-key.pub
  - name: reporting-server-config
    files:
      - reporting_server_config.py
